package com.startup.stepcounter.notification

object NotificationCode {
    const val WALKIE_STEP_NOTIFICATION_ID = 1
    const val ACTIVITY_PERMISSION_NOTIFICATION_ID = 2
    const val ARRIVE_NOTIFICATION_ID = 3
    const val HATCHING_NOTIFICATION_ID = 4

    const val WALKIE_STEP_NOTIFICATION_CHANNEL_ID = "WALKIE_STEP_NOTIFICATION_CHANNEL_ID"
    const val WALKIE_STEP_NOTIFICATION_CHANNEL_NAME = "WALKIE_STEP_NOTIFICATION_CHANNEL_NAME"
    const val WALKIE_STEP_NOTIFICATION_DESCRIPTION = "WALKIE_STEP_NOTIFICATION_DESCRIPTION"

    const val WALKIE_EGG_INDUCTION_NOTIFICATION_CHANNEL_ID = "WALKIE_STEP_NOTIFICATION_CHANNEL_ID"
    const val WALKIE_EGG_INDUCTION_NOTIFICATION_CHANNEL_NAME = "WALKIE_STEP_NOTIFICATION_CHANNEL_NAME"
    const val WALKIE_EGG_INDUCTION_NOTIFICATION_DESCRIPTION = "WALKIE_STEP_NOTIFICATION_DESCRIPTION"
    
    const val ARRIVE_NOTIFICATION_CHANNEL_ID = "ARRIVE_NOTIFICATION_CHANNEL_ID"
    const val ARRIVE_NOTIFICATION_CHANNEL_NAME = "ARRIVE_NOTIFICATION_CHANNEL_NAME"
    const val ARRIVE_NOTIFICATION_DESCRIPTION = "ARRIVE_NOTIFICATION_DESCRIPTION"

    const val HATCHING_NOTIFICATION_CHANNEL_ID = "HATCHING_NOTIFICATION_CHANNEL_ID"
    const val HATCHING_NOTIFICATION_CHANNEL_NAME = "HATCHING_NOTIFICATION_CHANNEL_NAME"
    const val HATCHING_NOTIFICATION_DESCRIPTION = "HATCHING_NOTIFICATION_DESCRIPTION"

    const val ACTIVITY_PERMISSION_NOTIFICATION_CHANNEL_ID = "ACTIVITY_PERMISSION_NOTIFICATION_CHANNEL_ID"
    const val ACTIVITY_PERMISSION_NOTIFICATION_CHANNEL_NAME = "ACTIVITY_PERMISSION_NOTIFICATION_CHANNEL_NAME"
    const val ACTIVITY_PERMISSION_NOTIFICATION_DESCRIPTION = "ACTIVITY_PERMISSION_NOTIFICATION_DESCRIPTION"

    const val DAILY_GOAL_ACHIEVED_NOTIFICATION_ID = 5
    const val DAILY_GOAL_ACHIEVED_NOTIFICATION_CHANNEL_ID = "DAILY_GOAL_ACHIEVED_NOTIFICATION_CHANNEL_ID"
    const val DAILY_GOAL_ACHIEVED_NOTIFICATION_CHANNEL_NAME = "일일 목표 달성"
    const val DAILY_GOAL_ACHIEVED_NOTIFICATION_DESCRIPTION = "일일 걸음수 목표를 달성했을 때 알림을 받습니다"

}